const DATA={
 '한국':[['가야금','현악기','pluck'],['대금','관악기','flute'],['해금','현악기','bow'],['장구','타악기','drum']],
 '중국':[['고쟁','현악기','pluck'],['얼후','현악기','bow'],['비파','현악기','pluck'],['디즈','관악기','flute']],
 '일본':[['고토','현악기','pluck'],['샤미센','현악기','pluck'],['샤쿠하치','관악기','flute'],['타이코','타악기','drum']],
 '인도':[['시타르','현악기','pluck'],['타블라','타악기','drum'],['반수리','관악기','flute'],['탄푸라','현악기','bow']],
 '중동':[['우드','현악기','pluck'],['카눈','현악기','pluck'],['네이','관악기','flute'],['다르부카','타악기','drum']],
 '유럽':[['바이올린','현악기','bow'],['첼로','현악기','bow'],['하프','현악기','pluck'],['플루트','관악기','flute']],
 '아프리카':[['코라','현악기','pluck'],['젬베','타악기','drum'],['칼림바','건반형','bell'],['발라폰','타악기','bell']],
 '남미':[['차랑고','현악기','pluck'],['케나','관악기','flute'],['팬플루트','관악기','flute'],['봄보','타악기','drum']],
 '현대악기':[['피아노','건반악기','piano'],['전자피아노','건반악기','piano'],['어쿠스틱 기타','현악기','pluck'],['일렉 기타','현악기','guitar'],['베이스 기타','현악기','bass'],['드럼 세트','타악기','drum'],['신시사이저','전자악기','synth'],['전자 패드','전자악기','pad'],['색소폰','관악기','sax'],['트럼펫','관악기','brass'],['808 베이스','전자악기','bass'],['EDM 신스','전자악기','synth']],
 '오케스트라':[['그랜드 피아노','건반악기','piano'],['바이올린 섹션','현악기','bow'],['비올라','현악기','bow'],['첼로 섹션','현악기','bow'],['콘트라베이스','현악기','bass'],['프렌치 호른','금관악기','brass'],['팀파니','타악기','drum'],['합창 패드','성악·패드','pad']]
};

const PROFILES={
 vacation:{keywords:['휴가','여행','복귀','출근','일상','내일부터','내일'],title:'다시 시작하는 내일',mood:'아쉬움에서 희망으로',genre:'팝 록 + 포크',bpm:108,meter:'4/4',key:'D Major',vocal:'편안한 남성 중음, 후렴에서 힘차게',modern:['어쿠스틱 기타','피아노','베이스 기타','드럼 세트'],arrange:'어쿠스틱 기타로 담백하게 시작하고 후렴에서 드럼과 베이스를 열어 밝게 전환'},
 love:{keywords:['사랑','연인','보고 싶','그리워','설렘','눈빛','마음'],title:'너에게 가는 노래',mood:'따뜻하고 설레는',genre:'모던 팝 발라드',bpm:92,meter:'4/4',key:'A Major',vocal:'남녀 듀엣, 벌스는 부드럽고 후렴은 중고음 하모니',modern:['피아노','어쿠스틱 기타','베이스 기타','드럼 세트'],arrange:'피아노와 기타로 가까이 시작해 후렴에서 현악기와 하모니를 넓게 확장'},
 breakup:{keywords:['이별','헤어','떠나','끝난','잊지 못','눈물','아픈'],title:'남겨진 계절',mood:'절제된 슬픔과 긴 여운',genre:'컨템포러리 발라드',bpm:72,meter:'6/8',key:'B Minor',vocal:'낮은 중음에서 시작해 마지막 후렴만 절정',modern:['그랜드 피아노','첼로 섹션','전자 패드','베이스 기타'],arrange:'피아노 단음과 첼로로 여백을 두고 6/8의 흔들림 위에 감정을 천천히 상승'},
 healing:{keywords:['자연','산','바다','비','새벽','치유','편안','쉼','하늘','바람'],title:'마음을 씻는 바람',mood:'맑고 편안한 치유',genre:'어쿠스틱 뉴에이지 팝',bpm:76,meter:'6/8',key:'G Major',vocal:'숨결이 자연스러운 맑은 보컬',modern:['피아노','어쿠스틱 기타','전자 패드','첼로 섹션'],arrange:'자연의 여백을 살린 피아노와 패드, 후렴에서만 부드러운 현악기를 추가'},
 celebration:{keywords:['생일','축하','기념','응원','성공','고마워','감사'],title:'오늘은 너의 날',mood:'밝고 따뜻한 축하',genre:'업리프팅 팝',bpm:118,meter:'4/4',key:'C Major',vocal:'밝은 리드 보컬과 모두 따라 부르는 합창',modern:['피아노','일렉 기타','베이스 기타','드럼 세트'],arrange:'손뼉 리듬과 피아노로 시작해 후렴에서 기타와 단체 하모니를 크게 전개'},
 dance:{keywords:['춤','댄스','클럽','밤중','리듬','신나','파티','네온'],title:'오늘 밤 더 높이',mood:'강렬하고 자유로운',genre:'2026 댄스 팝',bpm:126,meter:'4/4',key:'F# Minor',vocal:'선명한 여성 리드와 짧은 남성 랩',modern:['EDM 신스','808 베이스','드럼 세트','신시사이저'],arrange:'짧은 신스 훅으로 시작해 프리코러스에서 비트를 덜고 드롭형 후렴으로 폭발'},
 hope:{keywords:['희망','꿈','도전','시작','힘내','다시','미래','용기'],title:'한 걸음 더',mood:'차분하게 시작해 벅차오르는 희망',genre:'팝 록 앤섬',bpm:112,meter:'4/4',key:'E Major',vocal:'단단한 중음 리드와 마지막 합창',modern:['피아노','일렉 기타','베이스 기타','드럼 세트'],arrange:'피아노 리듬에서 시작해 기타와 라이브 드럼을 단계적으로 쌓아 마지막에 합창'},
 generic:{keywords:[],title:'오늘의 이야기',mood:'담백하고 진솔한',genre:'모던 팝',bpm:96,meter:'4/4',key:'G Major',vocal:'가사가 또렷한 자연스러운 중음 보컬',modern:['피아노','어쿠스틱 기타','베이스 기타','드럼 세트'],arrange:'벌스는 보컬 중심으로 단순하게, 후렴에서 리듬과 화음을 넓혀 이야기의 핵심을 강조'}
};

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let region='한국',selected=new Set(),chosenWords=new Set(),ctx=null,timers=[],lastProfile=PROFILES.generic,scoreNotes=[],scoreEntries=[],barOverrides={};
const speedBpm={slow:72,medium:98,fast:126};
const WORDS=['첫 만남','눈빛','미소','기다림','설렘','약속','그리움','사랑','이별','재회','함께','우정','가족','응원','용기','희망','꿈','새로운 시작','내일','여행','바다','숲','바람','비','별빛','달빛','새벽','도시','고향','추억','감사','축하'];
const WORD_LINES={'첫 만남':'처음 마주친 그날의 공기까지','눈빛':'말보다 먼저 다가온 너의 눈빛','미소':'지친 하루를 밝혀 주던 미소','기다림':'긴 기다림도 사랑이 되었고','설렘':'작은 설렘이 심장을 두드려','약속':'우리의 약속을 마음에 새겨','그리움':'그리움은 밤마다 노래가 되고','사랑':'사랑은 두 사람의 길을 비추고','이별':'이별 뒤에도 따뜻한 기억은 남아','재회':'돌고 돌아 다시 마주친 우리','함께':'혼자가 아닌 우리 함께 걸어가','우정':'오랜 우정은 든든한 노래가 되고','가족':'언제나 돌아갈 가족의 품','응원':'언제나 네 편에서 응원할게','용기':'작은 용기가 내일을 열어','희망':'가슴속 희망을 다시 밝혀','꿈':'놓지 않은 꿈이 길이 되어','새로운 시작':'끝이 아닌 새로운 시작 앞에서','내일':'내일은 오늘보다 환하게','여행':'함께한 여행은 길이 되어 남아','바다':'푸른 바다가 마음을 안아 주고','숲':'고요한 숲이 숨을 쉬게 해','바람':'부드러운 바람이 걱정을 씻어','비':'창가의 비가 추억을 두드려','별빛':'별빛 아래 두 마음이 가까워져','달빛':'달빛이 조용히 우리를 비추고','새벽':'새벽 끝에서 새로운 빛을 만나','도시':'도시의 불빛 사이 꿈을 찾아','고향':'그리운 고향의 길을 떠올려','추억':'소중한 추억을 가슴에 품고','감사':'고마운 마음을 노래에 담아','축하':'오늘의 기쁨을 함께 축하해'};
function renderWordChoices(){$('#wordChoices').innerHTML=WORDS.map(w=>`<button class="chip ${chosenWords.has(w)?'active':''}" data-word="${w}">${w}</button>`).join('');$$('[data-word]').forEach(b=>b.onclick=()=>{const w=b.dataset.word;chosenWords.has(w)?chosenWords.delete(w):chosenWords.add(w);renderWordChoices()})}

function renderRegions(){
 $('#regions').innerHTML=Object.keys(DATA).map(r=>`<button class="chip ${r===region?'active':''}" data-region="${r}">${r}</button>`).join('');
 $$('#regions button').forEach(b=>b.onclick=()=>{region=b.dataset.region;renderRegions();renderInstruments()});
}
function renderInstruments(){
 $('#instruments').innerHTML=DATA[region].map(([n,t])=>`<div class="instrument ${selected.has(n)?'active':''}"><b>${n}</b><span>${region} · ${t}</span><button data-name="${n}" class="hear">▶ 소리</button> <button data-pick="${n}">${selected.has(n)?'✓ 선택됨':'+ 선택'}</button></div>`).join('');
 $$('.hear').forEach(b=>b.onclick=e=>{e.stopPropagation();previewTone(findInstrument(b.dataset.name)[2])});
 $$('[data-pick]').forEach(b=>b.onclick=()=>{const n=b.dataset.pick;selected.has(n)?selected.delete(n):selected.add(n);renderInstruments();updateInfo()});
}
function findInstrument(name){for(const list of Object.values(DATA)){const f=list.find(x=>x[0]===name);if(f)return f}return ['피아노','건반악기','piano']}
function detectProfile(story){const s=story.toLowerCase();let best=PROFILES.generic,score=0;for(const p of Object.values(PROFILES)){const n=p.keywords.filter(k=>s.includes(k)).length;if(n>score){best=p;score=n}}return {...best}}
function genrePreset(name){if(/발라드/.test(name))return{bpm:82,meter:'4/4',arrange:'피아노와 어쿠스틱 악기로 시작해 후렴에서 현악기와 보컬 화음을 넓게 확장'};if(/EDM|하우스|테크노|트랜스|댄스|디스코|개러지|퓨처 베이스/.test(name))return{bpm:126,meter:'4/4',arrange:'짧은 전자 훅과 선명한 킥으로 시작해 후렴에서 넓은 신스와 리듬을 확장'};if(/힙합|랩|트랩|R&B|소울|펑크|가스펠/.test(name))return{bpm:94,meter:'4/4',arrange:'보컬과 그루브를 전면에 두고 벌스는 절제하며 후렴에서 코러스와 리듬을 강화'};if(/록/.test(name))return{bpm:116,meter:'4/4',arrange:'기타 리프와 라이브 드럼을 단계적으로 쌓고 마지막 후렴에서 밴드 사운드를 확장'};if(/재즈|보사노바|스윙|블루스/.test(name))return{bpm:96,meter:'4/4',arrange:'피아노와 베이스의 여백 있는 화음 위에 자연스러운 스윙과 즉흥 응답을 배치'};if(/트로트/.test(name))return{bpm:112,meter:'4/4',arrange:'또렷한 2박 리듬과 꺾임을 살리고 후렴에서 브라스와 코러스를 강조'};if(/왈츠/.test(name))return{bpm:90,meter:'3/4',arrange:'한 마디 세 박의 흐름을 살려 피아노와 현악기가 우아하게 회전'};if(/뉴에이지|앰비언트|로파이/.test(name))return{bpm:76,meter:'6/8',arrange:'피아노와 패드의 여백을 살리고 잔잔한 악기 응답으로 감정을 유지'};if(/라틴|레게|아프로|플라멩코/.test(name))return{bpm:104,meter:'4/4',arrange:'싱코페이션과 타악기 그루브를 중심으로 후렴에서 합주를 밝게 확장'};if(/영화|오케스트라|뮤지컬|합창/.test(name))return{bpm:84,meter:'4/4',arrange:'작은 피아노 모티프로 시작해 현악기·관악기·합창을 단계적으로 확장'};if(/국악|전통|월드|중국풍|일본풍|인도|중동/.test(name))return{bpm:98,meter:'4/4',arrange:'전통악기 독주와 현대 리듬이 서로 응답하며 후렴에서 세계 악기 합주로 확장'};return{bpm:100,meter:'4/4',arrange:'보컬 중심의 간결한 벌스에서 시작해 후렴에서 리듬과 화음을 선명하게 확장'}}
function activeProfile(){
 const custom=$('#customWords')?.value||'',hook=$('#hookLine')?.value||'',clues=[...chosenWords].join(' ');
 const p=detectProfile(`${$('#story').value.trim()} ${clues} ${custom} ${hook}`);
 const mood=$('#mood').value,genre=$('#genre').value,vocal=$('#vocal').value,speed=$('#speed').value;
 if(mood!=='auto')p.mood=mood;if(genre!=='auto'){p.genre=genre;const g=genrePreset(genre);p.arrange=g.arrange;if(speed==='auto'){p.bpm=g.bpm;p.meter=g.meter}}if(vocal!=='auto')p.vocal=vocal;
 if(speed!=='auto'){p.bpm=speedBpm[speed];if(speed==='slow'&&p.meter==='4/4')p.meter='6/8'}
 return p;
}
function analyze(){
 const story=$('#story').value.trim();if(!story){toast('노래 이야기를 먼저 입력해 주세요');$('#story').focus();return null}
 lastProfile=activeProfile();const traditional=DATA[region].slice(0,2).map(x=>x[0]);
 $('#analysisResult').textContent=`이야기 해석: ${lastProfile.mood}\n장르: ${lastProfile.genre}\n빠르기·박자: ${lastProfile.bpm} BPM · ${lastProfile.meter}\n조성: ${lastProfile.key}\n보컬: ${lastProfile.vocal}\n추천 조합: ${traditional.concat(lastProfile.modern).join(', ')}\n편곡 방향: ${lastProfile.arrange}`;
 updateInfo();toast('이야기와 음악을 분석했습니다');return lastProfile;
}
function audio(){return ctx||(ctx=new (window.AudioContext||window.webkitAudioContext)())}
function tone(type,freq=440,when=0,dur=.55,vol=.1){
 const c=audio(),t=c.currentTime+when,g=c.createGain(),o=c.createOscillator(),filter=c.createBiquadFilter();
 const waves={pluck:'triangle',bow:'sawtooth',flute:'sine',bell:'sine',drum:'square',piano:'triangle',guitar:'sawtooth',bass:'sine',synth:'sawtooth',pad:'sine',sax:'square',brass:'sawtooth'};
 o.type=waves[type]||'sine';o.frequency.setValueAtTime(type==='drum'?freq/2:freq,t);filter.type='lowpass';filter.frequency.value=type==='bass'?500:type==='pad'?1200:2600;o.connect(filter);filter.connect(g);g.connect(c.destination);
 if(['pluck','drum','piano','guitar','bell'].includes(type)){g.gain.setValueAtTime(vol,t);g.gain.exponentialRampToValueAtTime(.001,t+dur)}else{g.gain.setValueAtTime(.001,t);g.gain.linearRampToValueAtTime(vol,t+.08);g.gain.exponentialRampToValueAtTime(.001,t+dur)}o.start(t);o.stop(t+dur+.03);
}
function previewTone(type){audio().resume();const seq=type==='drum'?[110,90,130,90]:type==='bass'?[130.8,146.8,164.8,196]:[261.6,329.6,392,523.2];seq.forEach((f,i)=>tone(type,f,i*.18,.5,.09))}
function stop(){timers.forEach(clearTimeout);timers=[];if(ctx){ctx.close();ctx=null}$('#pulse').classList.remove('playing')}
function playMix(){
 stop();const p=activeProfile();audio().resume();const beat=60/p.bpm,chosen=[...selected];if(!chosen.length){autoPick();return playMix()}const roots=p.key.includes('Minor')?[220,174.6,196,164.8]:[261.6,196,220,174.6],mode=/댄스|EDM/.test(p.genre)?'dance':/발라드|뉴에이지/.test(p.genre)?'ballad':/트로트/.test(p.genre)?'trot':/록/.test(p.genre)?'rock':'fusion';let count=0;$('#pulse').classList.add('playing');
 const loop=()=>{const root=roots[Math.floor(count/4)%4];chosen.slice(0,6).forEach((n,j)=>{const type=findInstrument(n)[2];let note=root*(type==='bass'?.5:1);if(mode==='ballad')note*=[1,1.25,1.5,2][count%4];if(mode==='dance'&&type==='synth')note*=count%2?1.5:2;if(mode==='trot')note*=count%2?1.25:1;if(mode==='rock'&&['guitar','pluck'].includes(type))note*=count%4<2?1:1.5;const hit=type!=='drum'||mode==='dance'||(mode==='rock'&&count%2===0)||(mode==='ballad'&&count%4===0)||(mode==='trot'&&count%2===0)||(mode==='fusion'&&count%3!==1);if(hit)tone(type,type==='drum'?90:note,j*.018,mode==='ballad'?beat*1.5:beat*.8,.045)});count++;if(count<40)timers.push(setTimeout(loop,beat*1000));else $('#pulse').classList.remove('playing')};loop();toast(`${mode} 장르 전용 반주를 재생합니다`)
}
function autoPick(){
 const p=activeProfile();selected.clear();DATA[region].slice(0,2).forEach(x=>selected.add(x[0]));p.modern.forEach(n=>selected.add(n));lastProfile=p;renderInstruments();updateInfo();toast(`${region} 전통악기와 현대악기를 조합했습니다`)
}
function updateInfo(){const p=activeProfile();$('#musicInfo').textContent=`${p.bpm} BPM · ${p.meter}박자 · ${p.key} · ${[...selected].join(' + ')||'악기를 선택해 주세요'}`}

function hasBatchim(text){const chars=[...text].filter(c=>/[가-힣]/.test(c));if(!chars.length)return false;return (chars.at(-1).charCodeAt(0)-0xAC00)%28!==0}
function joinKorean(names){if(names.length<2)return names[0]||'악기';const head=names.slice(0,-1).join(', '),last=names.at(-1);return `${head}${hasBatchim(head)?'과':'와'} ${last}`}

const LYRICS={
 vacation:{v1:['달력 끝에 접어 둔 짧은 여행','느리게 흐르던 하루가 참 좋았지','사진 속 웃음은 가방에 챙겨 두고','익숙한 거리로 다시 돌아갈 시간'],pre:['아쉬운 마음도 오늘까지만','새 아침이 문 앞에서 날 기다려'],chorus:['짧았던 휴가는 추억으로 남기고','내일이면 다시 길을 나서야 해','쉬어 간 만큼 더 가벼운 발걸음','새로운 하루를 힘차게 시작해'],v2:['잠시 멈춰 보니 알 것만 같아','평범한 하루도 소중했다는 걸','바쁜 시간 속 지칠 때가 오면','오늘의 바람을 다시 꺼내 볼게'],bridge:['끝은 또 다른 시작이 되니까','아쉬움 대신 설렘을 안고 가']},
 love:{v1:['처음 네 눈빛이 내게 머문 순간','익숙한 하루가 조금 달라졌어','말하지 않아도 번지는 미소','나도 모르게 너를 따라 웃었어'],pre:['한 걸음만 더 가까이','우리의 시간이 시작돼'],chorus:['자꾸자꾸 너만 보여','자꾸자꾸 네 생각 나','같은 리듬 같은 마음','오늘부터 우리 함께해'],v2:['서툰 인사도 특별해지는 밤','짧은 메시지도 오래 남아 있어','서로의 하루를 천천히 나누며','두 사람의 계절을 만들어 가'],bridge:['멀리 돌아온 날에도','내가 먼저 네 손을 잡을게']},
 breakup:{v1:['불을 끈 방 안에 남은 네 이름','지우려 할수록 더 선명해져','함께 걷던 길은 그대로인데','나 혼자 계절을 건너고 있어'],pre:['괜찮다는 짧은 한마디','오늘은 왜 이렇게 어려운지'],chorus:['우리의 시간이 여기 멈춰도','사랑했던 날까지 지우진 않을게','아픈 기억마저 품고 나면','언젠가 나도 웃을 수 있겠지'],v2:['익숙한 번호를 누르다 멈추고','보내지 못한 말을 접어 두었어','서로의 내일을 위해 놓아주는 일','그것도 사랑이라 믿어 보려고'],bridge:['마지막 눈물이 마르면','나의 계절을 다시 걸어갈게']},
 healing:{v1:['도시의 소리를 잠시 내려놓고','바람이 부르는 길을 따라가','맑은 물소리가 마음을 두드리면','숨겨 둔 피로가 천천히 풀려'],pre:['말하지 않아도 괜찮아','자연은 조용히 안아 주니까'],chorus:['바람아 내 마음을 씻어 줘','햇살아 지친 어깨를 감싸 줘','서두르지 않아도 괜찮다고','오늘의 하늘이 내게 말해 줘'],v2:['깊은 숲 사이로 번지는 빛처럼','작은 희망이 다시 피어나고','돌아갈 일상이 기다리고 있어도','지금 이 평온을 오래 간직할게'],bridge:['천천히 숨을 들이쉬면','나는 다시 나에게 돌아와']},
 celebration:{v1:['기다려 온 오늘이 드디어 왔어','환한 웃음으로 문을 열어 봐','네가 걸어온 수많은 날들이','이 순간을 더욱 빛나게 해'],pre:['두 눈을 감고 소원을 빌어','행복이 네 곁으로 오고 있어'],chorus:['오늘은 오늘은 너의 날','세상에서 가장 환하게 웃어','한 걸음 두 걸음 손을 맞잡고','우리 함께 끝까지 축하할게'],v2:['힘들었던 날도 잘 견뎌 냈어','그 모든 시간이 널 만들었어','앞으로 펼쳐질 새로운 장면마다','좋은 일들이 가득하기를'],bridge:['언제든 네 편이 되어','가장 큰 목소리로 응원할게']},
 dance:{v1:['네온이 번지는 한밤의 거리','심장이 먼저 비트를 알아봐','복잡한 생각은 문밖에 두고','오늘의 리듬에 몸을 맡겨 봐'],pre:['하나 둘 숨을 고르고','다시 불이 켜지는 순간'],chorus:['더 높이 더 높이 손을 들어','오늘 밤 우리는 멈추지 않아','한 바퀴 돌아서 웃어 봐','이 리듬 끝까지 함께 달려가'],v2:['거울 속 모습도 자유로워져','누가 뭐래도 지금은 나의 시간','발끝의 열기가 무대를 깨우고','점점 더 크게 세상이 흔들려'],bridge:['비트가 잠시 멈춘 그때','우리의 함성이 다시 터져']},
 hope:{v1:['막막한 길 앞에 멈춰 선 날도','작은 빛 하나는 사라지지 않아','늦었다는 말에 고개 숙이지 마','너의 시간은 바로 지금이니까'],pre:['천천히 가도 괜찮아','멈추지만 않으면 돼'],chorus:['한 걸음 더 앞으로 가자','넘어져도 다시 일어나','오늘의 용기가 길이 되어','내일의 우리를 만나게 할 거야'],v2:['수많은 걱정이 발을 붙잡아도','가슴속 꿈까지 놓지는 말아 줘','함께 걷는 사람이 곁에 있다면','어두운 터널도 끝이 보일 테니'],bridge:['가장 긴 밤을 지나면','새로운 태양이 떠오를 거야']},
 generic:{v1:['오늘의 마음을 조용히 펼쳐','숨겨 둔 이야기를 노래에 담아','서툰 말 사이 진심을 모아서','나만의 멜로디로 천천히 걸어가'],pre:['누군가 이 노래를 듣는다면','내 마음을 조금은 알아주기를'],chorus:['오늘의 이야기를 노래해','꾸미지 않은 나의 목소리로','짧은 한 줄도 진심이 된다면','이 노래는 이미 충분하니까'],v2:['지나간 시간과 다가올 날들이','하나의 리듬으로 이어져 가고','평범했던 순간 하나하나가','세상에 하나뿐인 노래가 돼'],bridge:['마지막 음이 멈춘 뒤에도','따뜻한 마음은 남아 있기를']}
};
function profileKey(p){return Object.keys(PROFILES).find(k=>PROFILES[k].title===p.title)||'generic'}
function cleanWord(w){return w.replace(/공원\s*(밴츠|밴치|벤취)/g,'공원 벤치').replace(/\s+/g,' ').trim()}
function customWordLine(w){if(w.includes('공원 벤치'))return '공원 벤치에 나란히 앉아 웃던 오후';if(w.includes('바닷가'))return '바닷가에 나란히 남긴 두 사람의 발자국';if(w.includes('카페'))return '작은 카페 창가에 머물던 따뜻한 눈빛';return `${w}에 남겨 둔 우리만의 이야기를 기억해`}
function completeHook(h){const s=cleanWord(h);const known={'눈 맞추기':'눈을 맞추면 마음이 가까워져','돌아선':'돌아선 마음도 다시 피어나','함께':'오늘부터 우리 함께 걸어가','사랑':'사랑아 내 마음에 오래 머물러'};if(known[s])return known[s];if(!s)return '';if(s.length<=5||s.endsWith('기'))return `${s}, 우리 마음에 오래 남아`;return s}
const FINAL_GROWTH={
 love:[['자꾸자꾸 너만 보여','자꾸자꾸 네 생각 나','같은 리듬 같은 마음','조금 더 가까이 우리 함께해'],['이제는 너만 바라볼게','내일도 네 곁을 걸어갈게','같은 리듬 같은 마음','마지막까지 우리 함께 노래해']],
 generic:[['오늘의 이야기를 더 크게 노래해','꾸미지 않은 우리의 목소리로','짧은 한 줄도 서로에게 닿으면','이 노래는 새로운 시작이 되니까'],['마지막 이야기를 함께 노래해','따뜻한 마음을 하나로 모아서','오늘의 진심을 오래 기억하며','우리의 노래는 계속될 테니까']],
 healing:[['바람아 내 마음을 더 씻어 줘','햇살아 지친 어깨를 감싸 줘','천천히 걸어가도 괜찮다고','푸른 하늘이 다시 말해 줘'],['이제는 내 마음이 다시 피어나','햇살을 따라서 한 걸음 나아가','오늘의 평온을 가슴에 품고','새로운 나에게로 돌아갈게']]
};
function finalChorus(base,key,index){if(index===0)return base;return FINAL_GROWTH[key]?.[index-1]||base.map((line,i)=>i===base.length-1?'이 마음을 끝까지 함께 노래해':line)}
function makeLyrics(){
 const story=$('#story').value.trim();if(!story){toast('노래 이야기를 먼저 입력해 주세요');$('#story').focus();return}
 const p=analyze();if(!p)return;autoPick();const key=profileKey(p),l=LYRICS[key]||LYRICS.generic,mins=Number($('#length').value),inst=[...selected],intro=joinKorean(inst.slice(0,2)),outro=joinKorean(inst.slice(-2));const custom=$('#customWords').value.split(',').map(cleanWord).filter(Boolean),allWords=[...new Set([...custom,...chosenWords])],extra=allWords.slice(0,7).map(w=>WORD_LINES[w]||customWordLine(w)),hook=completeHook($('#hookLine').value),rich=$('#density').value==='rich',choruses=Number($('#chorusCount').value);
 const lines=[`[Intro]\n(${intro}${hasBatchim(intro)?'이':'가'} 곡의 분위기를 여는 연주)`,`[Verse 1]\n${l.v1.join('\n')}`,`[Pre-Chorus]\n${l.pre.join('\n')}`,`[Chorus]\n${l.chorus.join('\n')}`,`[Verse 2]\n${l.v2.join('\n')}`];
 if(extra.length)lines.push(`[Verse 3 · 핵심 단어]\n${extra.join('\n')}`);if(rich&&mins>=4)lines.push(`[Instrumental Interlude · 15초]\n(${intro}의 새로운 멜로디와 현대악기 리듬 변주)`);if(mins>2)lines.push(`[Bridge]\n${l.bridge.join('\n')}`);if(hook)lines.push(`[Hook]\n${hook}\n${hook}`);for(let i=1;i<=choruses;i++){const evolved=finalChorus(l.chorus,key,i-1);lines.push(`[Final Chorus${i>1?' '+i:''}]\n${i===choruses&&hook?hook+'\n':''}${evolved.join('\n')}`)}if(mins>=4.5)lines.push(`[Outro Chorus]\n${finalChorus(l.chorus,key,2).slice(0,2).join('\n')}\n우리의 이야기는 계속될 거야`);lines.push(`[Outro · 10초]\n(${outro}의 짧고 선명한 여운)`);
 $('#title').value=p.title;$('#lyrics').value=lines.join('\n\n');const blend=$('#blend').value,lang=$('#language').value;
 $('#style').value=`${p.genre}, ${p.bpm} BPM, ${p.meter} time, ${p.key}, 약 ${mins}분, ${p.mood}. ${p.vocal}, ${lang}. 악기: ${inst.join(', ')}. 전통악기 비율 ${blend}%. 편곡: ${p.arrange}. 벌스는 가사가 또렷하게 들리도록 악기를 절제하고, 후렴에서만 저역과 화음을 확장. 과도한 리버브·컴프레션·베이스 금지, 보컬을 전면에 배치.`;
 barOverrides={};createScore();toast('가사·음악 설계와 멜로디 악보를 만들었습니다')
}
const KEY_ROOTS={C:60,'C#':61,D:62,'D#':63,E:64,F:65,'F#':66,G:67,'G#':68,A:69,'A#':70,B:71};
const KEY_CHORDS={C:['C','G','Am','F'],D:['D','A','Bm','G'],E:['E','B','C#m','A'],F:['F','C','Dm','Bb'],'F#':['F#','C#','D#m','B'],G:['G','D','Em','C'],A:['A','E','F#m','D'],B:['B','F#','G#m','E'],'A Minor':['Am','F','C','G'],'B Minor':['Bm','G','D','A'],'C# Minor':['C#m','A','E','B'],'D Minor':['Dm','Bb','F','C'],'E Minor':['Em','C','G','D'],'F# Minor':['F#m','D','A','E'],'G# Minor':['G#m','E','B','F#']};
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function scoreSettings(){const p={...activeProfile()};if($('#scoreMode').value==='manual'){p.key=$('#manualKey').value;p.meter=$('#manualMeter').value;p.bpm=Math.max(45,Math.min(180,Number($('#manualBpm').value)||96))}return p}
function barRhythm(mode,total,bar,section,instrumental){if(instrumental)return total===4?[2,2]:[2,1];if(mode==='whole')return[total];if(mode==='half')return total===4?[2,2]:[2,1];if(mode==='quarter')return Array(total).fill(1);if(mode==='eighth')return Array(total*2).fill(.5);if(mode==='sixteenth')return Array(total*4).fill(.25);if(mode==='thirtysecond')return Array(total*8).fill(.125);const mixed=total===4?[[1,.5,.5,1,1],[.5,.5,1,2],[1,1,.5,.5,1],[2,.5,.5,1]]:[[1,.5,.5,1],[.5,.5,1,1],[1,1,1]];if(mode==='mixed')return mixed[bar%mixed.length];if(/Chorus|Hook/.test(section))return mixed[bar%mixed.length];if(/Bridge|Verse/.test(section))return bar%3===0?mixed[bar%mixed.length]:Array(total).fill(1);return total===4?[2,1,1]:[1,1,1]}
function syllableRhythm(count,total){const max=total*2,n=Math.max(1,Math.min(max,count));if(n===1)return[total];if(n<=total){const out=Array(n).fill(1);out[0]+=total-n;return out}const eighths=(n-total)*2,quarters=n-eighths;return[...Array(eighths).fill(.5),...Array(quarters).fill(1)]}
function dynamicMark(section,choice){if(choice!=='auto')return choice;if(/Final Chorus/.test(section))return'f';if(/Chorus|Hook/.test(section))return'mf';if(/Intro|Outro|Interlude/.test(section))return'p';return'mp'}
const DYNAMIC_VOLUME={pp:.025,p:.04,mp:.055,mf:.075,f:.095,ff:.12};
function lyricChars(text){return[...text.replace(/[\s,.!?·'"()]/g,'')].length}
function lyricCapacity(p){if(p.meter==='6/8')return p.bpm>=100?7:5;if(p.meter==='3/4')return p.bpm>=110?7:5;return p.bpm>=120?8:p.bpm<=80?5:6}
function splitLyric(text,max){const words=text.trim().split(/\s+/),parts=[];let line='';for(const word of words){const next=line?`${line} ${word}`:word;if(lyricChars(next)<=max){line=next;continue}if(line)parts.push(line);if(lyricChars(word)<=max){line=word;continue}const chars=[...word];while(chars.length>max)parts.push(chars.splice(0,max).join(''));line=chars.join('')}if(line)parts.push(line);return parts.length?parts:['']}
function pitchDegree(raw,mode,beat,count){if(mode==='low')return Math.max(0,raw-2);if(mode==='high')return Math.min(8,raw+3);if(mode==='middle')return Math.max(2,Math.min(6,raw));if(mode==='rise')return Math.min(8,beat+1);if(mode==='fall')return Math.max(0,count-beat);return raw}
function updateBarEditor(){const i=Number($('#barSelect').value),item=scoreEntries[i];if(!item)return;const o=barOverrides[i]||{};$('#barLyrics').value=o.text??item.text;$('#barRhythm').value=o.rhythm||'auto';$('#barPitch').value=o.pitch||'auto';$('#barDynamic').value=o.dynamic||'auto';updateBarCount()}
function updateBarCount(){const n=lyricChars($('#barLyrics').value),i=Number($('#barSelect').value),notes=scoreNotes.filter(x=>x.bar===i).length||6;$('#barCount').textContent=`${n}글자 · ${notes}음표`;$('#barWarning').textContent=n>notes?`글자가 음표보다 ${n-notes}개 많습니다. 8분음표를 선택하거나 가사를 줄여 주세요.`:`한 음표에 한 글자로 배치할 수 있습니다.`;$('#barWarning').classList.toggle('over',n>notes)}
function noteFraction(d){return d>=4?'1/1':d>=2?'1/2':d>=1?'1/4':d>=.5?'1/8':d>=.25?'1/16':'1/32'}
function drawFractionLabels(){const svg=$('#scoreSvg');if(!svg)return;const p=scoreSettings(),total=p.meter==='6/8'?3:Number(p.meter.split('/')[0]),ns='http://www.w3.org/2000/svg';scoreEntries.forEach((_,bar)=>{const notes=scoreNotes.filter(n=>n.bar===bar),x0=75+(bar%4)*207.5,top=65+Math.floor(bar/4)*155;let elapsed=0;notes.forEach(n=>{const text=document.createElementNS(ns,'text'),x=x0+18+(elapsed/total)*178,y=top+42-n.degree*6;text.setAttribute('x',x);text.setAttribute('y',top+61);text.setAttribute('text-anchor','middle');text.setAttribute('font-size',n.duration<.5?'6':'8');text.setAttribute('fill','#6f3bd2');text.textContent=noteFraction(n.duration);svg.appendChild(text);const extra=n.duration<=.125?2:n.duration<=.25?1:0;for(let k=1;k<=extra;k++){const path=document.createElementNS(ns,'path');path.setAttribute('d',`M ${x+6} ${y-30+k*6} q 13 7 4 18`);path.setAttribute('fill','none');path.setAttribute('stroke','#111');path.setAttribute('stroke-width','1.6');svg.appendChild(path)}elapsed+=n.duration});if(notes[0]){const dyn=document.createElementNS(ns,'text');dyn.setAttribute('x',x0+175);dyn.setAttribute('y',top+100);dyn.setAttribute('font-size','14');dyn.setAttribute('font-style','italic');dyn.setAttribute('font-weight','800');dyn.setAttribute('fill','#b02a62');dyn.textContent=notes[0].dynamic;svg.appendChild(dyn)}})}
function vexDuration(d){return d>=4?'w':d>=2?'h':d>=1?'q':d>=.5?'8':d>=.25?'16':'32'}
function midiKey(midi){const names=['c','c#','d','d#','e','f','f#','g','g#','a','a#','b'],oct=Math.floor(midi/12)-1;return`${names[midi%12]}/${oct}`}
function renderEngravedScore(){const VF=window.VexFlow;if(!VF||!scoreEntries.length)return false;const p=scoreSettings(),meter=p.meter.split('/').map(Number),barsPerSystem=window.innerWidth<720?2:2,systems=Math.ceil(scoreEntries.length/barsPerSystem),width=920,height=systems*175+35,host=$('#scoreSheet');host.innerHTML=`<div class="engraved-title">${esc($('#title').value||'MARU SONG')} · 정식 오선악보</div><div id="vexScore"></div>`;const renderer=new VF.Renderer($('#vexScore'),VF.Renderer.Backends.SVG);renderer.resize(width,height);const context=renderer.getContext(),keyName=p.key.replace(' Major','').replace(' Minor','m'),chordRoot=p.key.split(' ')[0],chords=KEY_CHORDS[p.key]||KEY_CHORDS[chordRoot]||KEY_CHORDS.G;let globalIndex=0;for(let bar=0;bar<scoreEntries.length;bar++){const system=Math.floor(bar/barsPerSystem),slot=bar%barsPerSystem,x=35+slot*440,y=25+system*175,stave=new VF.Stave(x,y,425);if(slot===0)stave.addClef('treble').addTimeSignature(p.meter).addKeySignature(keyName);if(bar===0||scoreEntries[bar-1].section!==scoreEntries[bar].section)stave.setText(scoreEntries[bar].section,VF.Modifier.Position.ABOVE,{shift_y:-8});stave.setContext(context).draw();const source=scoreNotes.filter(n=>n.bar===bar),letters=[...scoreEntries[bar].text.replace(/\s/g,'')],notes=source.map((n,i)=>{const duration=vexDuration(n.duration)+(scoreEntries[bar].instrumental?'r':''),note=new VF.StaveNote({clef:'treble',keys:[scoreEntries[bar].instrumental?'b/4':midiKey(n.midi)],duration});if(!scoreEntries[bar].instrumental&&letters[i])note.addModifier(new VF.Annotation(letters[i]).setFont('sans-serif',11).setVerticalJustification(VF.Annotation.VerticalJustify.BOTTOM));if(i===0){note.addModifier(new VF.Annotation(chords[bar%4]).setFont('sans-serif',13,'bold').setVerticalJustification(VF.Annotation.VerticalJustify.TOP));note.addModifier(new VF.Annotation(n.dynamic).setFont('serif',13,'italic').setVerticalJustification(VF.Annotation.VerticalJustify.BOTTOM).setJustification(VF.Annotation.HorizontalJustify.LEFT))}if(note.setAttribute)note.setAttribute('data-note',String(globalIndex));if(note.addClass)note.addClass('score-note');globalIndex++;return note});const voice=new VF.Voice({num_beats:meter[0],beat_value:meter[1]}).setStrict(false);voice.addTickables(notes);new VF.Formatter().joinVoices([voice]).format([voice],slot===0?330:380);voice.draw(context,stave);VF.Beam.generateBeams(notes).forEach(beam=>beam.setContext(context).draw())}const svg=$('#vexScore svg');if(svg){svg.id='scoreSvg';svg.setAttribute('viewBox',`0 0 ${width} ${height}`);svg.setAttribute('aria-label','가사 음절과 리듬을 맞춘 정식 전체 악보')}return true}
function fillBarEditor(){if(!renderEngravedScore())drawFractionLabels();const current=$('#barSelect').value;$('#barSelect').innerHTML=scoreEntries.map((e,i)=>`<option value="${i}">${i+1}마디 · ${esc(e.section)} · ${esc(e.text)}</option>`).join('');$('#barSelect').value=current&&scoreEntries[current]?current:'0';updateBarEditor()}
function applyBarEdit(){const i=Number($('#barSelect').value);if(!scoreEntries[i])return toast('수정할 마디를 선택해 주세요');barOverrides[i]={text:$('#barLyrics').value.trim(),rhythm:$('#barRhythm').value,pitch:$('#barPitch').value,dynamic:$('#barDynamic').value};createScore();$('#barSelect').value=String(i);updateBarEditor();toast(`${i+1}마디 가사·음표·음세기 수정을 적용했습니다`)}
function createScore(){
 if(!$('#lyrics').value){toast('먼저 노래 설계를 만들어 주세요');return}const p=scoreSettings(),minor=p.key.includes('Minor'),rootName=p.key.split(' ')[0],key=minor?p.key:rootName,root=KEY_ROOTS[rootName]||67,scale=minor?[0,2,3,5,7,8,10]:[0,2,4,5,7,9,11],six=p.meter==='6/8',total=six?3:Number(p.meter.split('/')[0]),patterns=six?[0,2,4,3,2,1,1,3,5,4,3,2,2,4,6,5,4,2]:[0,2,4,3,1,3,5,4,2,4,6,5,3,2,1,0],entries=[];let section='';
 const capacity=lyricCapacity(p);$('#lyrics').value.split('\n').forEach(raw=>{const line=raw.trim();if(!line)return;if(/^\[.+\]$/.test(line)){section=line.slice(1,-1);return}const instrumental=/^\(.+\)$/.test(line),text=line.replace(/^\(|\)$/g,'');if(instrumental)entries.push({section,text,instrumental:true});else splitLyric(text,capacity).forEach(part=>entries.push({section,text:part,instrumental:false}))});entries.forEach((e,i)=>{if(barOverrides[i]?.text!==undefined)e.text=barOverrides[i].text});scoreEntries=entries;const bars=entries.length,systems=Math.ceil(bars/4),height=65+systems*155+30,rhythmMode=$('#rhythmMode').value,dynamicChoice=$('#dynamics').value;scoreNotes=[];let noteIndex=0;
 for(let bar=0;bar<bars;bar++){const override=barOverrides[bar]||{},mode=override.rhythm&&override.rhythm!=='auto'?override.rhythm:rhythmMode,durations=mode==='auto'&&!entries[bar].instrumental?syllableRhythm(lyricChars(entries[bar].text),total):barRhythm(mode,total,bar,entries[bar].section,entries[bar].instrumental),barDynamic=override.dynamic&&override.dynamic!=='auto'?override.dynamic:dynamicMark(entries[bar].section,dynamicChoice);durations.forEach((duration,beat)=>{const base=patterns[(noteIndex+bar)%patterns.length],raw=pitchDegree(base,override.pitch||'auto',beat,durations.length),oct=raw>=7?1:0,degree=raw%7,midi=root+scale[degree]+oct*12;scoreNotes.push({midi,degree:degree+oct*7,bar,beat,duration,dynamic:barDynamic});noteIndex++})}
 const chords=KEY_CHORDS[key]||KEY_CHORDS.G;let body='';for(let system=0;system<systems;system++){const top=65+system*155,left=70,right=900;for(let l=0;l<5;l++)body+=`<line x1="${left}" y1="${top+l*12}" x2="${right}" y2="${top+l*12}" stroke="#222"/>`;body+=`<text x="25" y="${top+42}" font-size="52">𝄞</text><text x="58" y="${top+22}" font-size="18">${p.meter.split('/')[0]}</text><text x="58" y="${top+42}" font-size="18">${p.meter.split('/')[1]}</text>`;for(let b=0;b<4;b++){const bar=system*4+b;if(bar>=bars)break;const item=entries[bar],x0=75+b*207.5,previous=entries[bar-1];body+=`<line x1="${x0}" y1="${top}" x2="${x0}" y2="${top+48}" stroke="#222"/>`;if(!previous||previous.section!==item.section)body+=`<text x="${x0+5}" y="${top-25}" font-size="12" font-weight="800" fill="#7040a0">${esc(item.section)}</text>`;body+=`<text x="${x0+8}" y="${top-8}" font-size="16" font-weight="700">${esc(chords[bar%4])}</text>`;const notes=scoreNotes.filter(n=>n.bar===bar);let elapsed=0;notes.forEach(n=>{const x=x0+18+(elapsed/total)*178,y=top+42-n.degree*6,index=scoreNotes.indexOf(n),open=n.duration>=2,stem=n.duration<4,flag=n.duration<=.5,dot=n.duration===1.5||n.duration===3;body+=`<g class="score-note" data-note="${index}"><ellipse cx="${x}" cy="${y}" rx="7" ry="5" transform="rotate(-18 ${x} ${y})" fill="${open?'white':'#111'}" stroke="#111" stroke-width="2"/>${stem?`<line x1="${x+6}" y1="${y}" x2="${x+6}" y2="${y-30}" stroke="#111" stroke-width="2"/>`:''}${flag?`<path d="M ${x+6} ${y-30} q 13 7 4 18" fill="none" stroke="#111" stroke-width="2"/>`:''}${dot?`<circle cx="${x+12}" cy="${y}" r="2.2" fill="#111"/>`:''}</g>`;elapsed+=n.duration});body+=`<text x="${x0+7}" y="${top+75}" font-size="12.5" ${item.instrumental?'font-style="italic" fill="#555"':''}>${esc(item.text)}</text>`}const first=entries[system*4];body+=`<text x="78" y="${top+100}" font-size="17" font-weight="800" font-style="italic">${dynamicMark(first?.section||'',dynamicChoice)}</text><line x1="900" y1="${top}" x2="900" y2="${top+48}" stroke="#222" stroke-width="2"/>`}
 const title=esc($('#title').value||'MARU SONG'),modeLabel=$('#scoreMode').value==='manual'?'수동':'자동';$('#scoreSheet').innerHTML=`<svg id="scoreSvg" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 930 ${height}" role="img" aria-label="${title} 전체 멜로디 악보"><rect width="930" height="${height}" fill="white"/><text x="465" y="28" text-anchor="middle" font-size="22" font-weight="800">${title} · Full Song Melody</text>${body}<text x="465" y="${height-8}" text-anchor="middle" font-size="12">MARU WORLD MUSIC MAKER V0.7 · 음절 맞춤·마디 편집 악보</text></svg>`;$('#scoreMeta').textContent=`${modeLabel} · ${p.key} · ${p.meter}박자 · ${p.bpm} BPM · 전체 ${bars}마디 · 음표 ${scoreNotes.length}개 · 한 마디 권장 ${capacity}글자`;fillBarEditor();toast(`${modeLabel} 설정으로 가사와 음표를 맞춘 전체 악보를 만들었습니다`)
}
function playScore(){if(!scoreNotes.length){createScore();if(!scoreNotes.length)return}stop();const p=scoreSettings(),quarter=60/p.bpm;audio().resume();let elapsed=0;scoreNotes.forEach((n,i)=>{const start=elapsed*quarter,dur=n.duration*quarter,vol=DYNAMIC_VOLUME[n.dynamic]||.07;tone('piano',440*Math.pow(2,(n.midi-69)/12),start,dur*.88,vol);timers.push(setTimeout(()=>{$$('.score-note').forEach(x=>x.classList.remove('active'));$(`[data-note="${i}"]`)?.classList.add('active')},start*1000));elapsed+=n.duration});timers.push(setTimeout(()=>{$$('.score-note').forEach(x=>x.classList.remove('active'))},elapsed*quarter*1000));toast('전주부터 아웃트로까지 전체 곡을 재생합니다')}
function downloadScore(){const svg=$('#scoreSvg');if(!svg){toast('먼저 악보를 만들어 주세요');return}const blob=new Blob([new XMLSerializer().serializeToString(svg)],{type:'image/svg+xml;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${($('#title').value||'MARU-SONG').replace(/[\\/:*?"<>|]/g,'_')}-악보.svg`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('다운로드 폴더에 악보를 저장했습니다')}
function updateScoreMode(){const manual=$('#scoreMode').value==='manual';['manualKey','manualMeter','manualBpm'].forEach(id=>$('#'+id).disabled=!manual);if(manual){const p=activeProfile();$('#manualKey').value=p.key;$('#manualMeter').value=p.meter;$('#manualBpm').value=p.bpm}if($('#scoreSvg'))createScore()}
function toast(s){const t=$('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1900)}
function save(){if(!$('#lyrics').value){toast('먼저 노래 설계를 만들어 주세요');return}const songs=JSON.parse(localStorage.getItem('maruSongs')||'[]');songs.unshift({title:$('#title').value||'제목 없음',lyrics:$('#lyrics').value,style:$('#style').value,date:new Date().toLocaleDateString('ko-KR')});localStorage.setItem('maruSongs',JSON.stringify(songs.slice(0,30)));renderSaved();toast('브라우저에 임시 저장했습니다')}
function downloadTxt(){if(!$('#lyrics').value){toast('먼저 노래 설계를 만들어 주세요');return}const title=$('#title').value||'MARU-SONG',safe=title.replace(/[\\/:*?"<>|]/g,'_'),content=`제목: ${title}\n\n${$('#lyrics').value}\n\n[음악 스타일]\n${$('#style').value}\n`;const blob=new Blob(['\ufeff'+content],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${safe}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('다운로드 폴더에 TXT 파일을 저장했습니다')}
async function copySuno(){if(!$('#lyrics').value)return toast('먼저 노래 설계를 만들어 주세요');const text=`[Title]\n${$('#title').value||'제목 없음'}\n\n[Lyrics]\n${$('#lyrics').value}\n\n[Style of Music]\n${$('#style').value}`;await navigator.clipboard.writeText(text);toast('Suno용 제목·전체 가사·스타일을 모두 복사했습니다')}
function renderSaved(){const songs=JSON.parse(localStorage.getItem('maruSongs')||'[]');$('#savedSongs').innerHTML=songs.length?songs.map((s,i)=>`<article><b>${s.title}</b><p>${s.date}</p><button class="secondary" data-load="${i}">열기</button> <button class="danger" data-del="${i}">삭제</button></article>`).join(''):'<p>아직 임시 저장한 노래가 없습니다.</p>';$$('[data-load]').forEach(b=>b.onclick=()=>{const s=songs[b.dataset.load];$('#title').value=s.title;$('#lyrics').value=s.lyrics;$('#style').value=s.style;scrollTo({top:document.body.scrollHeight/2,behavior:'smooth'})});$$('[data-del]').forEach(b=>b.onclick=()=>{songs.splice(Number(b.dataset.del),1);localStorage.setItem('maruSongs',JSON.stringify(songs));renderSaved()})}

$('#analyzeStory').onclick=analyze;$('#autoPick').onclick=autoPick;$('#playMix').onclick=playMix;$('#stopMix').onclick=stop;$('#createSong').onclick=makeLyrics;$('#saveSong').onclick=save;$('#downloadTxt').onclick=downloadTxt;$('#copySuno').onclick=copySuno;$('#createScore').onclick=createScore;$('#playScore').onclick=playScore;$('#stopScore').onclick=stop;$('#printScore').onclick=()=>{if(!$('#scoreSvg'))return toast('먼저 악보를 만들어 주세요');window.print()};$('#downloadScore').onclick=downloadScore;$('#scoreMode').onchange=updateScoreMode;$('#barSelect').onchange=updateBarEditor;$('#barLyrics').oninput=updateBarCount;$('#applyBar').onclick=applyBarEdit;['manualKey','manualMeter','manualBpm','dynamics','rhythmMode'].forEach(id=>$('#'+id).onchange=()=>{if($('#scoreSvg'))createScore()});$('#blend').oninput=e=>$('#blendValue').textContent=e.target.value+'%';
['speed','genre','mood','vocal'].forEach(id=>$('#'+id).onchange=updateInfo);$$('[data-copy]').forEach(b=>b.onclick=async()=>{const el=$('#'+b.dataset.copy);await navigator.clipboard.writeText(el.value);toast('복사했습니다')});
renderWordChoices();renderRegions();renderInstruments();autoPick();renderSaved();updateScoreMode();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js?v=0.8.0');
